# Generated by Django 4.1.7 on 2023-06-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarlavka', '0002_remove_order_order_items_order_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(to='guitarlavka.orderitem'),
        ),
    ]
