# Generated by Django 4.1.7 on 2023-06-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarlavka', '0002_alter_cart_session_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Імя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Прізвище'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='telephone',
            field=models.CharField(default=1, max_length=100, verbose_name='Номер телефону'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адреса доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(max_length=100, verbose_name='Коментарій до замовлення'),
        ),
    ]
