# Generated by Django 4.1.7 on 2023-06-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarlavka', '0008_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Імя'),
            preserve_default=False,
        ),
    ]
