# Generated by Django 4.1.7 on 2023-06-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitarlavka', '0009_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
